/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WorkspaceChatRouteImport } from './routes/_workspace.chat'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace.dashboard'
import { Route as WorkspaceDraftRouteImport } from './routes/_workspace.draft'
import { Route as WorkspaceHistoryRouteImport } from './routes/_workspace.history'
import { Route as WorkspaceJudgmentsRouteImport } from './routes/_workspace.judgments'
import { Route as WorkspaceProfileRouteImport } from './routes/_workspace.profile'
import { Route as WorkspaceSavedRouteImport } from './routes/_workspace.saved'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as WorkspaceDraftSlugRouteImport } from './routes/_workspace.draft.$slug'
import { Route as WorkspaceDraftPreviewRouteImport } from './routes/_workspace.draft.preview'
import { Route as WorkspaceDraftSaleDeedRouteImport } from './routes/_workspace.draft.sale-deed'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthSendOtpRouteImport } from './routes/api/auth/send-otp'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthVerifyOtpRouteImport } from './routes/api/auth/verify-otp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceChatRoute = WorkspaceChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDraftRoute = WorkspaceDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceHistoryRoute = WorkspaceHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceJudgmentsRoute = WorkspaceJudgmentsRouteImport.update({
  id: '/judgments',
  path: '/judgments',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProfileRoute = WorkspaceProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSavedRoute = WorkspaceSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDraftSlugRoute = WorkspaceDraftSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkspaceDraftRoute,
} as any)
const WorkspaceDraftPreviewRoute = WorkspaceDraftPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => WorkspaceDraftRoute,
} as any)
const WorkspaceDraftSaleDeedRoute = WorkspaceDraftSaleDeedRouteImport.update({
  id: '/sale-deed',
  path: '/sale-deed',
  getParentRoute: () => WorkspaceDraftRoute,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSendOtpRoute = ApiAuthSendOtpRouteImport.update({
  id: '/api/auth/send-otp',
  path: '/api/auth/send-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyOtpRoute = ApiAuthVerifyOtpRouteImport.update({
  id: '/api/auth/verify-otp',
  path: '/api/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof WorkspaceChatRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/draft': typeof WorkspaceDraftRouteWithChildren
  '/history': typeof WorkspaceHistoryRoute
  '/judgments': typeof WorkspaceJudgmentsRoute
  '/profile': typeof WorkspaceProfileRoute
  '/saved': typeof WorkspaceSavedRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/draft/$slug': typeof WorkspaceDraftSlugRoute
  '/draft/preview': typeof WorkspaceDraftPreviewRoute
  '/draft/sale-deed': typeof WorkspaceDraftSaleDeedRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof WorkspaceChatRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/draft': typeof WorkspaceDraftRouteWithChildren
  '/history': typeof WorkspaceHistoryRoute
  '/judgments': typeof WorkspaceJudgmentsRoute
  '/profile': typeof WorkspaceProfileRoute
  '/saved': typeof WorkspaceSavedRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/draft/$slug': typeof WorkspaceDraftSlugRoute
  '/draft/preview': typeof WorkspaceDraftPreviewRoute
  '/draft/sale-deed': typeof WorkspaceDraftSaleDeedRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_workspace/chat': typeof WorkspaceChatRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/draft': typeof WorkspaceDraftRouteWithChildren
  '/_workspace/history': typeof WorkspaceHistoryRoute
  '/_workspace/judgments': typeof WorkspaceJudgmentsRoute
  '/_workspace/profile': typeof WorkspaceProfileRoute
  '/_workspace/saved': typeof WorkspaceSavedRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/_workspace/draft/$slug': typeof WorkspaceDraftSlugRoute
  '/_workspace/draft/preview': typeof WorkspaceDraftPreviewRoute
  '/_workspace/draft/sale-deed': typeof WorkspaceDraftSaleDeedRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/auth/verify-otp': typeof ApiAuthVerifyOtpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/draft'
    | '/history'
    | '/judgments'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/api/assistant'
    | '/draft/$slug'
    | '/draft/preview'
    | '/draft/sale-deed'
    | '/api/auth/login'
    | '/api/auth/send-otp'
    | '/api/auth/signup'
    | '/api/auth/verify-otp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/dashboard'
    | '/draft'
    | '/history'
    | '/judgments'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/api/assistant'
    | '/draft/$slug'
    | '/draft/preview'
    | '/draft/sale-deed'
    | '/api/auth/login'
    | '/api/auth/send-otp'
    | '/api/auth/signup'
    | '/api/auth/verify-otp'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/signup'
    | '/_workspace/chat'
    | '/_workspace/dashboard'
    | '/_workspace/draft'
    | '/_workspace/history'
    | '/_workspace/judgments'
    | '/_workspace/profile'
    | '/_workspace/saved'
    | '/_workspace/settings'
    | '/api/assistant'
    | '/_workspace/draft/$slug'
    | '/_workspace/draft/preview'
    | '/_workspace/draft/sale-deed'
    | '/api/auth/login'
    | '/api/auth/send-otp'
    | '/api/auth/signup'
    | '/api/auth/verify-otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthSendOtpRoute: typeof ApiAuthSendOtpRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiAuthVerifyOtpRoute: typeof ApiAuthVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/chat': {
      id: '/_workspace/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof WorkspaceChatRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/draft': {
      id: '/_workspace/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof WorkspaceDraftRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/history': {
      id: '/_workspace/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof WorkspaceHistoryRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/judgments': {
      id: '/_workspace/judgments'
      path: '/judgments'
      fullPath: '/judgments'
      preLoaderRoute: typeof WorkspaceJudgmentsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/profile': {
      id: '/_workspace/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof WorkspaceProfileRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/saved': {
      id: '/_workspace/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof WorkspaceSavedRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/draft/$slug': {
      id: '/_workspace/draft/$slug'
      path: '/$slug'
      fullPath: '/draft/$slug'
      preLoaderRoute: typeof WorkspaceDraftSlugRouteImport
      parentRoute: typeof WorkspaceDraftRoute
    }
    '/_workspace/draft/preview': {
      id: '/_workspace/draft/preview'
      path: '/preview'
      fullPath: '/draft/preview'
      preLoaderRoute: typeof WorkspaceDraftPreviewRouteImport
      parentRoute: typeof WorkspaceDraftRoute
    }
    '/_workspace/draft/sale-deed': {
      id: '/_workspace/draft/sale-deed'
      path: '/sale-deed'
      fullPath: '/draft/sale-deed'
      preLoaderRoute: typeof WorkspaceDraftSaleDeedRouteImport
      parentRoute: typeof WorkspaceDraftRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/send-otp': {
      id: '/api/auth/send-otp'
      path: '/api/auth/send-otp'
      fullPath: '/api/auth/send-otp'
      preLoaderRoute: typeof ApiAuthSendOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-otp': {
      id: '/api/auth/verify-otp'
      path: '/api/auth/verify-otp'
      fullPath: '/api/auth/verify-otp'
      preLoaderRoute: typeof ApiAuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkspaceDraftRouteChildren {
  WorkspaceDraftSlugRoute: typeof WorkspaceDraftSlugRoute
  WorkspaceDraftPreviewRoute: typeof WorkspaceDraftPreviewRoute
  WorkspaceDraftSaleDeedRoute: typeof WorkspaceDraftSaleDeedRoute
}

const WorkspaceDraftRouteChildren: WorkspaceDraftRouteChildren = {
  WorkspaceDraftSlugRoute: WorkspaceDraftSlugRoute,
  WorkspaceDraftPreviewRoute: WorkspaceDraftPreviewRoute,
  WorkspaceDraftSaleDeedRoute: WorkspaceDraftSaleDeedRoute,
}

const WorkspaceDraftRouteWithChildren = WorkspaceDraftRoute._addFileChildren(
  WorkspaceDraftRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceChatRoute: typeof WorkspaceChatRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceDraftRoute: typeof WorkspaceDraftRouteWithChildren
  WorkspaceHistoryRoute: typeof WorkspaceHistoryRoute
  WorkspaceJudgmentsRoute: typeof WorkspaceJudgmentsRoute
  WorkspaceProfileRoute: typeof WorkspaceProfileRoute
  WorkspaceSavedRoute: typeof WorkspaceSavedRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceChatRoute: WorkspaceChatRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceDraftRoute: WorkspaceDraftRouteWithChildren,
  WorkspaceHistoryRoute: WorkspaceHistoryRoute,
  WorkspaceJudgmentsRoute: WorkspaceJudgmentsRoute,
  WorkspaceProfileRoute: WorkspaceProfileRoute,
  WorkspaceSavedRoute: WorkspaceSavedRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthSendOtpRoute: ApiAuthSendOtpRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiAuthVerifyOtpRoute: ApiAuthVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
